"""add_auditoria_datos_aprobados_table_and_estados_parciales

Revision ID: 5f0125256440
Revises: 34cf625b8606
Create Date: 2026-02-02 16:40:20.895043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5f0125256440'
down_revision: Union[str, None] = '34cf625b8606'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditoria_datos_aprobados',
    sa.Column('incapacidad_id', sa.UUID(), nullable=False, comment='ID de la incapacidad auditada'),
    sa.Column('fecha_inicio_aprobada', sa.Date(), nullable=False, comment='Fecha de inicio aprobada por el auditor'),
    sa.Column('fecha_fin_aprobada', sa.Date(), nullable=False, comment='Fecha de fin aprobada por el auditor'),
    sa.Column('dias_aprobados', sa.Integer(), nullable=False, comment='Cantidad de días aprobados (calculados automáticamente)'),
    sa.Column('cie10_aprobado', sa.String(length=10), nullable=False, comment='Código CIE-10 aprobado por el auditor'),
    sa.Column('diagnostico_aprobado', sa.String(length=500), nullable=False, comment='Descripción del diagnóstico aprobado'),
    sa.Column('observacion_auditoria', sa.Text(), nullable=False, comment='Observaciones del auditor justificando las modificaciones'),
    sa.Column('auditado_por_id', sa.UUID(), nullable=False, comment='ID del usuario auditor que aprobó estos datos'),
    sa.Column('fecha_auditoria', sa.DateTime(), nullable=False, comment='Fecha y hora de la auditoría'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['auditado_por_id'], ['usuario.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['incapacidad_id'], ['incapacidad.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('incapacidad_id', name='uq_auditoria_datos_incapacidad')
    )
    op.create_index(op.f('ix_auditoria_datos_aprobados_incapacidad_id'), 'auditoria_datos_aprobados', ['incapacidad_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auditoria_datos_aprobados_incapacidad_id'), table_name='auditoria_datos_aprobados')
    op.drop_table('auditoria_datos_aprobados')
    # ### end Alembic commands ###
