"""add previsionales tables

Revision ID: 11914a736f64
Revises: 87e66dac698e
Create Date: 2026-07-30 01:54:25.110317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '11914a736f64'
down_revision: Union[str, None] = '87e66dac698e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ite_historico',
    sa.Column('identificacion', sa.String(length=20), nullable=False, comment='Número de documento del afiliado'),
    sa.Column('fecha_inicial', sa.Date(), nullable=False, comment='Fecha inicial del periodo de ITE ya pagado'),
    sa.Column('fecha_final', sa.Date(), nullable=True, comment='Fecha final del periodo de ITE ya pagado'),
    sa.Column('valor_pagado', sa.Numeric(precision=15, scale=2), nullable=True, comment='Valor pagado en ese periodo'),
    sa.Column('fecha_pago', sa.Date(), nullable=True, comment='Fecha en que se realizó el pago'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ite_historico_ident_fecha_inicial', 'ite_historico', ['identificacion', 'fecha_inicial'], unique=False)
    op.create_table('siniestros_previsionales',
    sa.Column('identificacion', sa.String(length=20), nullable=False, comment='Número de documento del afiliado (no hay FK a empleado/empresa — dominio previsional)'),
    sa.Column('numero_siniestro', sa.String(length=50), nullable=False, comment='Número de siniestro (regla AM)'),
    sa.Column('origen', sa.String(length=50), nullable=True, comment='Origen del siniestro (regla AN)'),
    sa.Column('estado', sa.String(length=30), nullable=True, comment='Estado del siniestro (regla AO)'),
    sa.Column('fecha_aviso', sa.Date(), nullable=True, comment='Fecha de aviso del siniestro (regla AP)'),
    sa.Column('fecha_siniestro', sa.Date(), nullable=True, comment='Fecha de ocurrencia del siniestro (regla AP)'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_siniestros_previsionales_identificacion'), 'siniestros_previsionales', ['identificacion'], unique=False)
    op.create_table('solicitudes_previsionales',
    sa.Column('identificacion', sa.String(length=20), nullable=False, comment='Número de documento del afiliado'),
    sa.Column('radicado', sa.String(length=20), nullable=True, comment='Número de radicado de la solicitud en ARPIS'),
    sa.Column('tipo_ingreso', sa.String(length=20), nullable=True, comment='INICIAL|PRORROGA|TUTELA_I|TUTELA_P|AJUSTE'),
    sa.Column('fecha_inicial', sa.Date(), nullable=True, comment='Fecha inicial de la incapacidad solicitada'),
    sa.Column('fecha_final', sa.Date(), nullable=True, comment='Fecha final de la incapacidad solicitada'),
    sa.Column('dia_181', sa.Date(), nullable=True, comment='Día 181 según la AFP (regla AE, base de AF)'),
    sa.Column('fecha_crie', sa.Date(), nullable=True, comment='Fecha CRIE reportada por la AFP (regla AG)'),
    sa.Column('observacion', sa.Text(), nullable=True, comment='Observación libre de la solicitud original'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solicitudes_previsionales_identificacion'), 'solicitudes_previsionales', ['identificacion'], unique=False)
    op.create_table('lotes_previsionales',
    sa.Column('nombre_archivo', sa.String(length=255), nullable=False, comment='Nombre del archivo Excel cargado (p.ej. RADICADOS_AUDITORIA_20260706.xlsx)'),
    sa.Column('estado', sa.String(length=20), server_default='CARGADO', nullable=False, comment='Estado del lote en el flujo CARGADO->EN_AUDITORIA->AUDITADO->LIQUIDADO->RESPONDIDO'),
    sa.Column('fecha_cargue', postgresql.TIMESTAMP(timezone=True), nullable=False, comment='Fecha/hora en que se cargó el archivo (distinta de created_at si se reprocesa)'),
    sa.Column('cargado_por_id', sa.UUID(), nullable=True, comment='Usuario que cargó el archivo del lote'),
    sa.Column('total_filas', sa.Integer(), server_default='0', nullable=False, comment='Total de filas leídas del archivo Excel (incluye filas con errores de parseo)'),
    sa.Column('total_incapacidades', sa.Integer(), server_default='0', nullable=False, comment='Total de incapacidades previsionales creadas exitosamente a partir del lote'),
    sa.Column('observaciones', sa.Text(), nullable=True, comment='Notas libres sobre el procesamiento del lote'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint("estado IN ('CARGADO', 'EN_AUDITORIA', 'AUDITADO', 'LIQUIDADO', 'RESPONDIDO')", name='chk_lote_previsional_estado'),
    sa.ForeignKeyConstraint(['cargado_por_id'], ['usuario.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incapacidades_previsionales',
    sa.Column('lote_id', sa.UUID(), nullable=False, comment='Lote de carga al que pertenece esta incapacidad'),
    sa.Column('tipo_identificacion', sa.String(length=5), nullable=True, comment='Tipo de documento del afiliado (CC, CE, etc.)'),
    sa.Column('identificacion', sa.String(length=20), nullable=True, comment='Número de documento del afiliado'),
    sa.Column('radicado', sa.String(length=20), nullable=True, comment='Número de radicado tal como llega del archivo AFP'),
    sa.Column('radicado_normalizado', sa.String(length=16), nullable=True, comment='Radicado normalizado (ver normalizar_radicado en arpis_export.py) — 16 dígitos'),
    sa.Column('tipo_ingreso', sa.String(length=20), nullable=True, comment='INICIAL|PRORROGA|TUTELA_I|TUTELA_P|AJUSTE (ver mapear_tipo_ingreso)'),
    sa.Column('fecha_inicial', sa.Date(), nullable=True, comment='Fecha inicial de la incapacidad'),
    sa.Column('fecha_final', sa.Date(), nullable=True, comment='Fecha final de la incapacidad'),
    sa.Column('dia_181_alfa', sa.Date(), nullable=True, comment='Día 181 auditado (Alfa) — usado por regla AB, distinto del de AFP'),
    sa.Column('dia_181_afp', sa.Date(), nullable=True, comment='Día 181 según la AFP — usado por reglas AE/AL'),
    sa.Column('dia_181_arpis', sa.Date(), nullable=True, comment='Día 181 según ARPIS — comparado contra dia_181_afp en regla AL'),
    sa.Column('fecha_crie', sa.Date(), nullable=True, comment='Fecha CRIE de la solicitud AFP — usada por regla AG'),
    sa.Column('fecha_radicacion_afp', sa.Date(), nullable=True, comment='Fecha de radicación ante la AFP'),
    sa.Column('fecha_radicacion_alfa', sa.Date(), nullable=True, comment='Fecha de radicación interna (Alfa)'),
    sa.Column('numero_siniestro', sa.String(length=50), nullable=True, comment='Número de siniestro asociado (regla AM-AP, AR)'),
    sa.Column('valor_afp', sa.Numeric(precision=15, scale=2), nullable=True, comment='Valor reportado por la AFP (regla AR, base de diferencia_valor_afp)'),
    sa.Column('cie10', sa.String(length=10), nullable=True, comment='Primer código CIE10 de la incapacidad'),
    sa.Column('observacion', sa.Text(), nullable=True, comment="Observación AFP cruda (fuente de 'Rad No. ' cuando el radicado no es numérico)"),
    sa.Column('observacion_causal', sa.Text(), nullable=True, comment='Observación de la causal de excepción (tutelas)'),
    sa.Column('aval', sa.String(length=2), nullable=True, comment="'SI'/'NO' — jamás se autocalcula (regla AC); solo lo define un auditor humano"),
    sa.Column('motivo_no_aval', sa.Text(), nullable=True, comment="Motivo cuando aval='NO'"),
    sa.Column('usuario_auditoria_id', sa.UUID(), nullable=True, comment='Usuario (AUDITOR_PREVISIONALES) que definió el aval'),
    sa.Column('fecha_auditoria', postgresql.TIMESTAMP(timezone=True), nullable=True, comment='Fecha/hora en que se definió el aval'),
    sa.Column('estado', sa.String(length=20), server_default='SIN_SINIESTRO', nullable=False, comment='SIN_SINIESTRO|CON_SINIESTRO|EN_AUDITORIA|AVALADO|NO_AVALADO|LIQUIDADO|PAGADO'),
    sa.Column('prorroga_de_id', sa.UUID(), nullable=True, comment='Incapacidad previa de la que esta es prórroga/tutela/ajuste (ver encadenar_prorrogas)'),
    sa.Column('incapacidad_origen_id', sa.UUID(), nullable=True, comment='Incapacidad original de la que esta es duplicado interno (ver es_duplicado_interno)'),
    sa.Column('es_duplicado_interno', sa.Boolean(), server_default='false', nullable=False, comment='True si esta fila es un duplicado interno de otra fila del mismo lote (regla AD)'),
    sa.Column('valor_auditado', sa.Numeric(precision=15, scale=2), nullable=True, comment='Valor calculado por liquidacion_previsional.calcular_valor()'),
    sa.Column('diferencia_valor_afp', sa.Numeric(precision=15, scale=2), nullable=True, comment='valor_auditado - valor_afp (glosa potencial)'),
    sa.Column('errores_carga', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Errores de parseo tolerante capturados durante la carga (CeldaInvalidaError por columna)'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint("aval IN ('SI', 'NO')", name='chk_incapacidad_previsional_aval'),
    sa.CheckConstraint("estado IN ('SIN_SINIESTRO', 'CON_SINIESTRO', 'EN_AUDITORIA', 'AVALADO', 'NO_AVALADO', 'LIQUIDADO', 'PAGADO')", name='chk_incapacidad_previsional_estado'),
    sa.CheckConstraint("tipo_ingreso IS NULL OR tipo_ingreso IN ('INICIAL', 'PRORROGA', 'TUTELA_I', 'TUTELA_P', 'AJUSTE')", name='chk_incapacidad_previsional_tipo_ingreso'),
    sa.ForeignKeyConstraint(['incapacidad_origen_id'], ['incapacidades_previsionales.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lote_id'], ['lotes_previsionales.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prorroga_de_id'], ['incapacidades_previsionales.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['usuario_auditoria_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incapacidades_previsionales_fecha_inicial'), 'incapacidades_previsionales', ['fecha_inicial'], unique=False)
    op.create_index(op.f('ix_incapacidades_previsionales_identificacion'), 'incapacidades_previsionales', ['identificacion'], unique=False)
    op.create_index(op.f('ix_incapacidades_previsionales_lote_id'), 'incapacidades_previsionales', ['lote_id'], unique=False)
    op.create_index('ix_incapacidades_previsionales_lote_ident_fecha', 'incapacidades_previsionales', ['lote_id', 'identificacion', 'fecha_inicial'], unique=False)
    op.create_table('periodos_previsionales',
    sa.Column('incapacidad_id', sa.UUID(), nullable=False, comment='Incapacidad previsional a la que pertenece este segmento'),
    sa.Column('orden', sa.Integer(), nullable=False, comment='Número secuencial del segmento (1-based), ver Segmento.orden'),
    sa.Column('fecha_inicio', sa.Date(), nullable=False, comment='Fecha inicial (inclusiva) del segmento'),
    sa.Column('fecha_fin', sa.Date(), nullable=False, comment='Fecha final (inclusiva) del segmento'),
    sa.Column('dias', sa.Integer(), nullable=False, comment='Días del segmento, conteo inclusivo (fecha_fin - fecha_inicio + 1)'),
    sa.Column('ibc', sa.Numeric(precision=15, scale=2), nullable=True, comment='Ingreso Base de Cotización del segmento — base real de la liquidación (NO salario)'),
    sa.Column('salario', sa.Numeric(precision=15, scale=2), nullable=True, comment='Salario reportado del segmento (informativo, no es la base)'),
    sa.Column('dias_cotizados', sa.Integer(), nullable=True, comment='Días cotizados del segmento según la AFP'),
    sa.Column('smlmv_aplicado', sa.Numeric(precision=15, scale=2), nullable=True, comment='SMLMV del año del segmento, usado como piso'),
    sa.Column('base_diaria', sa.Numeric(precision=15, scale=2), nullable=True, comment='Base mensual aplicada (max(IBC*0.5, SMLMV)) dividida entre 30'),
    sa.Column('valor_segmento', sa.Numeric(precision=15, scale=2), nullable=True, comment='Valor liquidado de este segmento (base_diaria * dias)'),
    sa.Column('grupo_arpis', sa.Integer(), nullable=True, comment='Grupo de salario ARPIS (1-3) al que pertenece este segmento — ver agrupar_salarios()'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['incapacidad_id'], ['incapacidades_previsionales.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_periodos_previsionales_incapacidad_id'), 'periodos_previsionales', ['incapacidad_id'], unique=False)
    op.create_table('senales_auditoria_previsionales',
    sa.Column('incapacidad_previsional_id', sa.UUID(), nullable=False, comment='Incapacidad previsional sobre la que se evaluó la regla'),
    sa.Column('codigo', sa.String(length=2), nullable=False, comment="Código de columna de la regla, 'AB'..'AT' (Senal.codigo)"),
    sa.Column('nombre', sa.String(length=100), nullable=False, comment='Nombre descriptivo de la regla (Senal.nombre)'),
    sa.Column('estado', sa.String(length=10), nullable=False, comment='OK|ALERTA|PENDIENTE|INFO — mismos 4 valores que EstadoSenal en auditoria_rules.py'),
    sa.Column('valor', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Senal.valor serializado — heterogéneo: date, dict, bool, str o list'),
    sa.Column('detalle', sa.Text(), nullable=True, comment='Senal.detalle — explicación libre del resultado'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint("estado IN ('OK', 'ALERTA', 'PENDIENTE', 'INFO')", name='chk_senal_auditoria_previsional_estado'),
    sa.ForeignKeyConstraint(['incapacidad_previsional_id'], ['incapacidades_previsionales.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_senales_auditoria_previsionales_incapacidad_previsional_id'), 'senales_auditoria_previsionales', ['incapacidad_previsional_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_senales_auditoria_previsionales_incapacidad_previsional_id'), table_name='senales_auditoria_previsionales')
    op.drop_table('senales_auditoria_previsionales')
    op.drop_index(op.f('ix_periodos_previsionales_incapacidad_id'), table_name='periodos_previsionales')
    op.drop_table('periodos_previsionales')
    op.drop_index('ix_incapacidades_previsionales_lote_ident_fecha', table_name='incapacidades_previsionales')
    op.drop_index(op.f('ix_incapacidades_previsionales_lote_id'), table_name='incapacidades_previsionales')
    op.drop_index(op.f('ix_incapacidades_previsionales_identificacion'), table_name='incapacidades_previsionales')
    op.drop_index(op.f('ix_incapacidades_previsionales_fecha_inicial'), table_name='incapacidades_previsionales')
    op.drop_table('incapacidades_previsionales')
    op.drop_table('lotes_previsionales')
    op.drop_index(op.f('ix_solicitudes_previsionales_identificacion'), table_name='solicitudes_previsionales')
    op.drop_table('solicitudes_previsionales')
    op.drop_index(op.f('ix_siniestros_previsionales_identificacion'), table_name='siniestros_previsionales')
    op.drop_table('siniestros_previsionales')
    op.drop_index('ix_ite_historico_ident_fecha_inicial', table_name='ite_historico')
    op.drop_table('ite_historico')
    # ### end Alembic commands ###
