"""Add refresh_token model

Revision ID: cfb087c2d5ef
Revises: 2329c303f650
Create Date: 2026-01-09 19:09:10.346845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cfb087c2d5ef'
down_revision: Union[str, None] = '2329c303f650'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('afiliado', 'estado',
               existing_type=postgresql.ENUM('ACTIVO', 'INACTIVO', 'SUSPENDIDO', name='estadoafiliado'),
               server_default=None,
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('afiliado', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('afiliado', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('afiliado', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint('afiliado_numero_poliza_key', 'afiliado', type_='unique')
    op.drop_index('idx_afiliado_documento', table_name='afiliado')
    op.drop_index('idx_afiliado_estado', table_name='afiliado')
    op.drop_index('idx_afiliado_nombre', table_name='afiliado')
    op.drop_index('idx_afiliado_poliza', table_name='afiliado')
    op.drop_index('idx_afiliado_sync', table_name='afiliado')
    op.create_index(op.f('ix_afiliado_external_id'), 'afiliado', ['external_id'], unique=False)
    op.create_index(op.f('ix_afiliado_numero_documento'), 'afiliado', ['numero_documento'], unique=False)
    op.create_index(op.f('ix_afiliado_numero_poliza'), 'afiliado', ['numero_poliza'], unique=True)
    op.add_column('auditoria_log', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('auditoria_log', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('auditoria_log', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('auditoria_log', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('idx_auditoria_accion', table_name='auditoria_log')
    op.drop_index('idx_auditoria_created_at', table_name='auditoria_log')
    op.drop_index('idx_auditoria_detalles', table_name='auditoria_log', postgresql_using='gin')
    op.drop_index('idx_auditoria_entidad', table_name='auditoria_log')
    op.drop_index('idx_auditoria_usuario', table_name='auditoria_log')
    op.create_index(op.f('ix_auditoria_log_accion'), 'auditoria_log', ['accion'], unique=False)
    op.create_index(op.f('ix_auditoria_log_created_at'), 'auditoria_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_auditoria_log_entidad'), 'auditoria_log', ['entidad'], unique=False)
    op.create_index(op.f('ix_auditoria_log_entidad_id'), 'auditoria_log', ['entidad_id'], unique=False)
    op.create_index(op.f('ix_auditoria_log_usuario_id'), 'auditoria_log', ['usuario_id'], unique=False)
    op.drop_constraint('auditoria_log_usuario_id_fkey', 'auditoria_log', type_='foreignkey')
    op.create_foreign_key(None, 'auditoria_log', 'usuario', ['usuario_id'], ['id'])
    op.add_column('documento', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('documento', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('documento', 'validado',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('documento', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('documento', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.drop_index('idx_documento_hash', table_name='documento')
    op.drop_index('idx_documento_incapacidad', table_name='documento')
    op.drop_index('idx_documento_tipo', table_name='documento')
    op.create_index(op.f('ix_documento_hash_sha256'), 'documento', ['hash_sha256'], unique=False)
    op.create_index(op.f('ix_documento_incapacidad_id'), 'documento', ['incapacidad_id'], unique=False)
    op.create_index(op.f('ix_documento_tipo_documento'), 'documento', ['tipo_documento'], unique=False)
    op.drop_constraint('documento_uploaded_by_id_fkey', 'documento', type_='foreignkey')
    op.create_foreign_key(None, 'documento', 'usuario', ['uploaded_by_id'], ['id'])
    op.alter_column('empleado', 'tipo_documento',
               existing_type=postgresql.ENUM('CC', 'CE', 'TI', 'PASAPORTE', 'PEP', name='tipodocumento'),
               type_=sa.String(length=10),
               existing_nullable=False)
    op.alter_column('empleado', 'email',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('empleado', 'genero',
               existing_type=postgresql.ENUM('M', 'F', 'O', name='genero'),
               type_=sa.String(length=10),
               existing_nullable=True)
    op.alter_column('empleado', 'estado',
               existing_type=postgresql.ENUM('ACTIVO', 'INACTIVO', 'RETIRADO', name='estadoempleado'),
               server_default=None,
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('empleado', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('empleado', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('empleado', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.drop_index('idx_empleado_documento', table_name='empleado')
    op.drop_index('idx_empleado_empresa', table_name='empleado')
    op.drop_index('idx_empleado_estado', table_name='empleado')
    op.drop_index('idx_empleado_nombre', table_name='empleado')
    op.drop_index('idx_empleado_sync', table_name='empleado')
    op.drop_constraint('uq_empleado_doc_empresa', 'empleado', type_='unique')
    op.create_index(op.f('ix_empleado_empresa_id'), 'empleado', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_empleado_estado'), 'empleado', ['estado'], unique=False)
    op.alter_column('empresa', 'estado',
               existing_type=postgresql.ENUM('ACTIVA', 'INACTIVA', 'SUSPENDIDA', name='estadoempresa'),
               server_default=None,
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('empresa', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('empresa', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('empresa', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint('empresa_nit_key', 'empresa', type_='unique')
    op.drop_index('idx_empresa_estado', table_name='empresa')
    op.drop_index('idx_empresa_nit', table_name='empresa')
    op.drop_index('idx_empresa_sync', table_name='empresa')
    op.create_index(op.f('ix_empresa_estado'), 'empresa', ['estado'], unique=False)
    op.create_index(op.f('ix_empresa_nit'), 'empresa', ['nit'], unique=True)
    op.alter_column('historial_estado', 'entity_type',
               existing_type=sa.VARCHAR(length=50),
               comment="Tipo de entidad: 'incapacidad', 'siniestro', etc.",
               existing_comment='Tipo de entidad: incapacidad, siniestro, etc.',
               existing_nullable=False)
    op.alter_column('historial_estado', 'fecha_cambio',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('historial_estado', 'cambiado_por_id',
               existing_type=sa.UUID(),
               comment='Usuario que realizó el cambio',
               existing_nullable=True)
    op.alter_column('historial_estado', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('historial_estado', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('historial_estado', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('incapacidad', 'estado',
               existing_type=postgresql.ENUM('RADICADA', 'EN_AUDITORIA', 'OBSERVADA', 'APROBADA', 'RECHAZADA', 'EN_PAGO', 'PAGADA', 'CANCELADA', name='estadoincapacidad'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('incapacidad', 'fecha_radicacion',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('incapacidad', 'fecha_auditoria',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('incapacidad', 'fecha_aprobacion',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('incapacidad', 'fecha_rechazo',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('incapacidad', 'prioridad',
               existing_type=postgresql.ENUM('BAJA', 'NORMAL', 'ALTA', 'URGENTE', name='prioridad'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('incapacidad', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('incapacidad', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('incapacidad', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.drop_index('idx_incapacidad_afiliado', table_name='incapacidad')
    op.drop_index('idx_incapacidad_auditado_por', table_name='incapacidad')
    op.drop_index('idx_incapacidad_empleado', table_name='incapacidad')
    op.drop_index('idx_incapacidad_empresa', table_name='incapacidad')
    op.drop_index('idx_incapacidad_estado', table_name='incapacidad')
    op.drop_index('idx_incapacidad_fecha_inicio', table_name='incapacidad')
    op.drop_index('idx_incapacidad_fecha_radicacion', table_name='incapacidad')
    op.drop_index('idx_incapacidad_numero', table_name='incapacidad')
    op.drop_index('idx_incapacidad_numero_siniestro', table_name='incapacidad')
    op.drop_index('idx_incapacidad_siniestro', table_name='incapacidad')
    op.drop_index('idx_incapacidad_tipo', table_name='incapacidad')
    op.drop_constraint('incapacidad_empleado_id_fkey', 'incapacidad', type_='foreignkey')
    op.drop_constraint('incapacidad_empresa_id_fkey', 'incapacidad', type_='foreignkey')
    op.drop_constraint('incapacidad_siniestro_id_fkey', 'incapacidad', type_='foreignkey')
    op.drop_constraint('incapacidad_afiliado_id_fkey', 'incapacidad', type_='foreignkey')
    op.drop_constraint('incapacidad_auditado_por_id_fkey', 'incapacidad', type_='foreignkey')
    op.drop_constraint('incapacidad_radicado_por_id_fkey', 'incapacidad', type_='foreignkey')
    op.drop_constraint('incapacidad_aprobado_por_id_fkey', 'incapacidad', type_='foreignkey')
    op.create_foreign_key(None, 'incapacidad', 'usuario', ['auditado_por_id'], ['id'])
    op.create_foreign_key(None, 'incapacidad', 'usuario', ['radicado_por_id'], ['id'])
    op.create_foreign_key(None, 'incapacidad', 'afiliado', ['afiliado_id'], ['id'])
    op.create_foreign_key(None, 'incapacidad', 'empresa', ['empresa_id'], ['id'])
    op.create_foreign_key(None, 'incapacidad', 'empleado', ['empleado_id'], ['id'])
    op.create_foreign_key(None, 'incapacidad', 'usuario', ['aprobado_por_id'], ['id'])
    op.create_foreign_key(None, 'incapacidad', 'siniestro', ['siniestro_id'], ['id'])
    op.add_column('orden_pago', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('orden_pago', 'estado_pago',
               existing_type=sa.VARCHAR(length=30),
               server_default=None,
               existing_nullable=False)
    op.alter_column('orden_pago', 'fecha_generacion',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('orden_pago', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('orden_pago', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('orden_pago', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.drop_index('idx_orden_beneficiario', table_name='orden_pago')
    op.drop_index('idx_orden_estado', table_name='orden_pago')
    op.drop_index('idx_orden_fecha_generacion', table_name='orden_pago')
    op.drop_index('idx_orden_incapacidad', table_name='orden_pago')
    op.drop_index('idx_orden_numero', table_name='orden_pago')
    op.drop_constraint('orden_pago_numero_orden_key', 'orden_pago', type_='unique')
    op.create_index(op.f('ix_orden_pago_estado_pago'), 'orden_pago', ['estado_pago'], unique=False)
    op.create_index(op.f('ix_orden_pago_incapacidad_id'), 'orden_pago', ['incapacidad_id'], unique=False)
    op.create_index(op.f('ix_orden_pago_numero_orden'), 'orden_pago', ['numero_orden'], unique=True)
    op.drop_constraint('orden_pago_aprobado_por_id_fkey', 'orden_pago', type_='foreignkey')
    op.drop_constraint('orden_pago_incapacidad_id_fkey', 'orden_pago', type_='foreignkey')
    op.drop_constraint('orden_pago_creado_por_id_fkey', 'orden_pago', type_='foreignkey')
    op.create_foreign_key(None, 'orden_pago', 'incapacidad', ['incapacidad_id'], ['id'])
    op.create_foreign_key(None, 'orden_pago', 'usuario', ['creado_por_id'], ['id'])
    op.create_foreign_key(None, 'orden_pago', 'usuario', ['aprobado_por_id'], ['id'])
    op.alter_column('siniestro', 'gravedad',
               existing_type=postgresql.ENUM('LEVE', 'MODERADA', 'GRAVE', 'MORTAL', name='gravedadsiniestro'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('siniestro', 'requirio_hospitalizacion',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('siniestro', 'estado',
               existing_type=postgresql.ENUM('REPORTADO', 'EN_INVESTIGACION', 'CERRADO', 'ANULADO', name='estadosiniestro'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('siniestro', 'fecha_reporte',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('siniestro', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('siniestro', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('siniestro', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.drop_index('idx_siniestro_empleado', table_name='siniestro')
    op.drop_index('idx_siniestro_empresa', table_name='siniestro')
    op.drop_index('idx_siniestro_estado', table_name='siniestro')
    op.drop_index('idx_siniestro_fecha', table_name='siniestro')
    op.drop_index('idx_siniestro_numero', table_name='siniestro')
    op.drop_index('idx_siniestro_sync', table_name='siniestro')
    op.drop_index('idx_siniestro_tipo', table_name='siniestro')
    op.drop_constraint('siniestro_empresa_id_fkey', 'siniestro', type_='foreignkey')
    op.drop_constraint('siniestro_empleado_id_fkey', 'siniestro', type_='foreignkey')
    op.create_foreign_key(None, 'siniestro', 'empresa', ['empresa_id'], ['id'])
    op.create_foreign_key(None, 'siniestro', 'empleado', ['empleado_id'], ['id'])
    op.add_column('usuario', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('usuario', 'estado',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('usuario', 'intentos_fallidos',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('usuario', 'token_version',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('usuario', 'must_change_password',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('usuario', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('usuario', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('usuario', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.drop_index('idx_usuario_email', table_name='usuario')
    op.drop_index('idx_usuario_empresa', table_name='usuario')
    op.drop_index('idx_usuario_rol', table_name='usuario')
    op.drop_index('idx_usuario_username', table_name='usuario')
    op.drop_constraint('usuario_email_key', 'usuario', type_='unique')
    op.drop_constraint('usuario_username_key', 'usuario', type_='unique')
    op.create_index(op.f('ix_usuario_email'), 'usuario', ['email'], unique=True)
    op.create_index(op.f('ix_usuario_empresa_id'), 'usuario', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_usuario_rol'), 'usuario', ['rol'], unique=False)
    op.create_index(op.f('ix_usuario_username'), 'usuario', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuario_username'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_rol'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_empresa_id'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_email'), table_name='usuario')
    op.create_unique_constraint('usuario_username_key', 'usuario', ['username'])
    op.create_unique_constraint('usuario_email_key', 'usuario', ['email'])
    op.create_index('idx_usuario_username', 'usuario', ['username'], unique=False)
    op.create_index('idx_usuario_rol', 'usuario', ['rol'], unique=False)
    op.create_index('idx_usuario_empresa', 'usuario', ['empresa_id'], unique=False)
    op.create_index('idx_usuario_email', 'usuario', ['email'], unique=False)
    op.alter_column('usuario', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('usuario', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('usuario', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False)
    op.alter_column('usuario', 'must_change_password',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('usuario', 'token_version',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('usuario', 'intentos_fallidos',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('usuario', 'estado',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'ACTIVO'::character varying"),
               existing_nullable=False)
    op.drop_column('usuario', 'metadata')
    op.drop_constraint(None, 'siniestro', type_='foreignkey')
    op.drop_constraint(None, 'siniestro', type_='foreignkey')
    op.create_foreign_key('siniestro_empleado_id_fkey', 'siniestro', 'empleado', ['empleado_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('siniestro_empresa_id_fkey', 'siniestro', 'empresa', ['empresa_id'], ['id'], ondelete='CASCADE')
    op.create_index('idx_siniestro_tipo', 'siniestro', ['tipo_siniestro'], unique=False)
    op.create_index('idx_siniestro_sync', 'siniestro', ['sync_source', 'external_id'], unique=False)
    op.create_index('idx_siniestro_numero', 'siniestro', ['numero_siniestro'], unique=False)
    op.create_index('idx_siniestro_fecha', 'siniestro', ['fecha_siniestro'], unique=False)
    op.create_index('idx_siniestro_estado', 'siniestro', ['estado'], unique=False)
    op.create_index('idx_siniestro_empresa', 'siniestro', ['empresa_id'], unique=False)
    op.create_index('idx_siniestro_empleado', 'siniestro', ['empleado_id'], unique=False)
    op.alter_column('siniestro', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('siniestro', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('siniestro', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False)
    op.alter_column('siniestro', 'fecha_reporte',
               existing_type=sa.DateTime(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('siniestro', 'estado',
               existing_type=postgresql.ENUM('REPORTADO', 'EN_INVESTIGACION', 'CERRADO', 'ANULADO', name='estadosiniestro'),
               server_default=sa.text("'REPORTADO'::estadosiniestro"),
               existing_nullable=False)
    op.alter_column('siniestro', 'requirio_hospitalizacion',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('siniestro', 'gravedad',
               existing_type=postgresql.ENUM('LEVE', 'MODERADA', 'GRAVE', 'MORTAL', name='gravedadsiniestro'),
               server_default=sa.text("'LEVE'::gravedadsiniestro"),
               existing_nullable=False)
    op.drop_constraint(None, 'orden_pago', type_='foreignkey')
    op.drop_constraint(None, 'orden_pago', type_='foreignkey')
    op.drop_constraint(None, 'orden_pago', type_='foreignkey')
    op.create_foreign_key('orden_pago_creado_por_id_fkey', 'orden_pago', 'usuario', ['creado_por_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('orden_pago_incapacidad_id_fkey', 'orden_pago', 'incapacidad', ['incapacidad_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('orden_pago_aprobado_por_id_fkey', 'orden_pago', 'usuario', ['aprobado_por_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_orden_pago_numero_orden'), table_name='orden_pago')
    op.drop_index(op.f('ix_orden_pago_incapacidad_id'), table_name='orden_pago')
    op.drop_index(op.f('ix_orden_pago_estado_pago'), table_name='orden_pago')
    op.create_unique_constraint('orden_pago_numero_orden_key', 'orden_pago', ['numero_orden'])
    op.create_index('idx_orden_numero', 'orden_pago', ['numero_orden'], unique=False)
    op.create_index('idx_orden_incapacidad', 'orden_pago', ['incapacidad_id'], unique=False)
    op.create_index('idx_orden_fecha_generacion', 'orden_pago', ['fecha_generacion'], unique=False)
    op.create_index('idx_orden_estado', 'orden_pago', ['estado_pago'], unique=False)
    op.create_index('idx_orden_beneficiario', 'orden_pago', ['beneficiario_id'], unique=False)
    op.alter_column('orden_pago', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('orden_pago', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('orden_pago', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False)
    op.alter_column('orden_pago', 'fecha_generacion',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('orden_pago', 'estado_pago',
               existing_type=sa.VARCHAR(length=30),
               server_default=sa.text("'GENERADA'::character varying"),
               existing_nullable=False)
    op.drop_column('orden_pago', 'metadata')
    op.drop_constraint(None, 'incapacidad', type_='foreignkey')
    op.drop_constraint(None, 'incapacidad', type_='foreignkey')
    op.drop_constraint(None, 'incapacidad', type_='foreignkey')
    op.drop_constraint(None, 'incapacidad', type_='foreignkey')
    op.drop_constraint(None, 'incapacidad', type_='foreignkey')
    op.drop_constraint(None, 'incapacidad', type_='foreignkey')
    op.drop_constraint(None, 'incapacidad', type_='foreignkey')
    op.create_foreign_key('incapacidad_aprobado_por_id_fkey', 'incapacidad', 'usuario', ['aprobado_por_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('incapacidad_radicado_por_id_fkey', 'incapacidad', 'usuario', ['radicado_por_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('incapacidad_auditado_por_id_fkey', 'incapacidad', 'usuario', ['auditado_por_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('incapacidad_afiliado_id_fkey', 'incapacidad', 'afiliado', ['afiliado_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('incapacidad_siniestro_id_fkey', 'incapacidad', 'siniestro', ['siniestro_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('incapacidad_empresa_id_fkey', 'incapacidad', 'empresa', ['empresa_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('incapacidad_empleado_id_fkey', 'incapacidad', 'empleado', ['empleado_id'], ['id'], ondelete='CASCADE')
    op.create_index('idx_incapacidad_tipo', 'incapacidad', ['tipo'], unique=False)
    op.create_index('idx_incapacidad_siniestro', 'incapacidad', ['siniestro_id'], unique=False)
    op.create_index('idx_incapacidad_numero_siniestro', 'incapacidad', ['numero_siniestro'], unique=False)
    op.create_index('idx_incapacidad_numero', 'incapacidad', ['numero'], unique=False)
    op.create_index('idx_incapacidad_fecha_radicacion', 'incapacidad', ['fecha_radicacion'], unique=False)
    op.create_index('idx_incapacidad_fecha_inicio', 'incapacidad', ['fecha_inicio'], unique=False)
    op.create_index('idx_incapacidad_estado', 'incapacidad', ['estado'], unique=False)
    op.create_index('idx_incapacidad_empresa', 'incapacidad', ['empresa_id'], unique=False)
    op.create_index('idx_incapacidad_empleado', 'incapacidad', ['empleado_id'], unique=False)
    op.create_index('idx_incapacidad_auditado_por', 'incapacidad', ['auditado_por_id'], unique=False)
    op.create_index('idx_incapacidad_afiliado', 'incapacidad', ['afiliado_id'], unique=False)
    op.alter_column('incapacidad', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('incapacidad', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('incapacidad', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False)
    op.alter_column('incapacidad', 'prioridad',
               existing_type=postgresql.ENUM('BAJA', 'NORMAL', 'ALTA', 'URGENTE', name='prioridad'),
               server_default=sa.text("'NORMAL'::prioridad"),
               existing_nullable=False)
    op.alter_column('incapacidad', 'fecha_rechazo',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('incapacidad', 'fecha_aprobacion',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('incapacidad', 'fecha_auditoria',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('incapacidad', 'fecha_radicacion',
               existing_type=sa.DateTime(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('incapacidad', 'estado',
               existing_type=postgresql.ENUM('RADICADA', 'EN_AUDITORIA', 'OBSERVADA', 'APROBADA', 'RECHAZADA', 'EN_PAGO', 'PAGADA', 'CANCELADA', name='estadoincapacidad'),
               server_default=sa.text("'RADICADA'::estadoincapacidad"),
               existing_nullable=False)
    op.alter_column('historial_estado', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('historial_estado', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('historial_estado', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('historial_estado', 'cambiado_por_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Usuario que realizó el cambio',
               existing_nullable=True)
    op.alter_column('historial_estado', 'fecha_cambio',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('historial_estado', 'entity_type',
               existing_type=sa.VARCHAR(length=50),
               comment='Tipo de entidad: incapacidad, siniestro, etc.',
               existing_comment="Tipo de entidad: 'incapacidad', 'siniestro', etc.",
               existing_nullable=False)
    op.drop_index(op.f('ix_empresa_nit'), table_name='empresa')
    op.drop_index(op.f('ix_empresa_estado'), table_name='empresa')
    op.create_index('idx_empresa_sync', 'empresa', ['sync_source', 'external_id'], unique=False)
    op.create_index('idx_empresa_nit', 'empresa', ['nit'], unique=False)
    op.create_index('idx_empresa_estado', 'empresa', ['estado'], unique=False)
    op.create_unique_constraint('empresa_nit_key', 'empresa', ['nit'])
    op.alter_column('empresa', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('empresa', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('empresa', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False)
    op.alter_column('empresa', 'estado',
               existing_type=sa.String(length=20),
               server_default=sa.text("'ACTIVA'::estadoempresa"),
               type_=postgresql.ENUM('ACTIVA', 'INACTIVA', 'SUSPENDIDA', name='estadoempresa'),
               existing_nullable=False)
    op.drop_index(op.f('ix_empleado_estado'), table_name='empleado')
    op.drop_index(op.f('ix_empleado_empresa_id'), table_name='empleado')
    op.create_unique_constraint('uq_empleado_doc_empresa', 'empleado', ['empresa_id', 'tipo_documento', 'numero_documento'])
    op.create_index('idx_empleado_sync', 'empleado', ['sync_source', 'external_id'], unique=False)
    op.create_index('idx_empleado_nombre', 'empleado', ['nombres', 'apellidos'], unique=False)
    op.create_index('idx_empleado_estado', 'empleado', ['estado'], unique=False)
    op.create_index('idx_empleado_empresa', 'empleado', ['empresa_id'], unique=False)
    op.create_index('idx_empleado_documento', 'empleado', ['tipo_documento', 'numero_documento'], unique=False)
    op.alter_column('empleado', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('empleado', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('empleado', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False)
    op.alter_column('empleado', 'estado',
               existing_type=sa.String(length=20),
               server_default=sa.text("'ACTIVO'::estadoempleado"),
               type_=postgresql.ENUM('ACTIVO', 'INACTIVO', 'RETIRADO', name='estadoempleado'),
               existing_nullable=False)
    op.alter_column('empleado', 'genero',
               existing_type=sa.String(length=10),
               type_=postgresql.ENUM('M', 'F', 'O', name='genero'),
               existing_nullable=True)
    op.alter_column('empleado', 'email',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('empleado', 'tipo_documento',
               existing_type=sa.String(length=10),
               type_=postgresql.ENUM('CC', 'CE', 'TI', 'PASAPORTE', 'PEP', name='tipodocumento'),
               existing_nullable=False)
    op.drop_constraint(None, 'documento', type_='foreignkey')
    op.create_foreign_key('documento_uploaded_by_id_fkey', 'documento', 'usuario', ['uploaded_by_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_documento_tipo_documento'), table_name='documento')
    op.drop_index(op.f('ix_documento_incapacidad_id'), table_name='documento')
    op.drop_index(op.f('ix_documento_hash_sha256'), table_name='documento')
    op.create_index('idx_documento_tipo', 'documento', ['tipo_documento'], unique=False)
    op.create_index('idx_documento_incapacidad', 'documento', ['incapacidad_id'], unique=False)
    op.create_index('idx_documento_hash', 'documento', ['hash_sha256'], unique=False)
    op.alter_column('documento', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('documento', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False)
    op.alter_column('documento', 'validado',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.drop_column('documento', 'metadata')
    op.drop_column('documento', 'updated_at')
    op.drop_constraint(None, 'auditoria_log', type_='foreignkey')
    op.create_foreign_key('auditoria_log_usuario_id_fkey', 'auditoria_log', 'usuario', ['usuario_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_auditoria_log_usuario_id'), table_name='auditoria_log')
    op.drop_index(op.f('ix_auditoria_log_entidad_id'), table_name='auditoria_log')
    op.drop_index(op.f('ix_auditoria_log_entidad'), table_name='auditoria_log')
    op.drop_index(op.f('ix_auditoria_log_created_at'), table_name='auditoria_log')
    op.drop_index(op.f('ix_auditoria_log_accion'), table_name='auditoria_log')
    op.create_index('idx_auditoria_usuario', 'auditoria_log', ['usuario_id'], unique=False)
    op.create_index('idx_auditoria_entidad', 'auditoria_log', ['entidad', 'entidad_id'], unique=False)
    op.create_index('idx_auditoria_detalles', 'auditoria_log', ['detalles'], unique=False, postgresql_using='gin')
    op.create_index('idx_auditoria_created_at', 'auditoria_log', [sa.text('created_at DESC')], unique=False)
    op.create_index('idx_auditoria_accion', 'auditoria_log', ['accion'], unique=False)
    op.alter_column('auditoria_log', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False)
    op.alter_column('auditoria_log', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.drop_column('auditoria_log', 'metadata')
    op.drop_column('auditoria_log', 'updated_at')
    op.drop_index(op.f('ix_afiliado_numero_poliza'), table_name='afiliado')
    op.drop_index(op.f('ix_afiliado_numero_documento'), table_name='afiliado')
    op.drop_index(op.f('ix_afiliado_external_id'), table_name='afiliado')
    op.create_index('idx_afiliado_sync', 'afiliado', ['sync_source', 'external_id'], unique=False)
    op.create_index('idx_afiliado_poliza', 'afiliado', ['numero_poliza'], unique=False)
    op.create_index('idx_afiliado_nombre', 'afiliado', ['nombres', 'apellidos'], unique=False)
    op.create_index('idx_afiliado_estado', 'afiliado', ['estado'], unique=False)
    op.create_index('idx_afiliado_documento', 'afiliado', ['tipo_documento', 'numero_documento'], unique=False)
    op.create_unique_constraint('afiliado_numero_poliza_key', 'afiliado', ['numero_poliza'])
    op.alter_column('afiliado', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('afiliado', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('afiliado', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False)
    op.alter_column('afiliado', 'estado',
               existing_type=sa.String(length=20),
               server_default=sa.text("'ACTIVO'::estadoafiliado"),
               type_=postgresql.ENUM('ACTIVO', 'INACTIVO', 'SUSPENDIDO', name='estadoafiliado'),
               existing_nullable=False)
    # ### end Alembic commands ###
