"""add_motivo_devolucion_to_pre_incapacidad

Revision ID: 58016e3f2c11
Revises: a30cd45b5b21
Create Date: 2026-06-07 17:42:20.376567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58016e3f2c11'
down_revision: Union[str, None] = 'a30cd45b5b21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pre_incapacidad', sa.Column('motivo_devolucion', sa.Text(), nullable=True))
    op.alter_column('validation_inconsistencia', 'codigo',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Machine-readable code',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('validation_inconsistencia', 'codigo',
               existing_type=sa.VARCHAR(length=100),
               comment='Machine-readable code',
               existing_nullable=False)
    op.drop_column('pre_incapacidad', 'motivo_devolucion')
    # ### end Alembic commands ###
