"""add_validation_inconsistencia_table

Revision ID: a30cd45b5b21
Revises: 874da694b916
Create Date: 2026-06-05 16:34:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a30cd45b5b21'
down_revision: Union[str, None] = '874da694b916'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('validation_inconsistencia',
    sa.Column('pre_incapacidad_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('incapacidad_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('categoria', sa.String(length=50), nullable=False, comment='FIELD_VALIDATION | BUSINESS_RULE | FRAUD_ALERT | INTEGRATION_CHECK'),
    sa.Column('severidad', sa.String(length=20), nullable=False, comment='ERROR | WARNING | INFO'),
    sa.Column('codigo', sa.String(length=100), nullable=False, comment='Machine-readable code'),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('campo_afectado', sa.String(length=100), nullable=True),
    sa.Column('valor_encontrado', sa.Text(), nullable=True),
    sa.Column('valor_esperado', sa.Text(), nullable=True),
    sa.Column('fecha_deteccion', sa.DateTime(), nullable=False),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['incapacidad_id'], ['incapacidad.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pre_incapacidad_id'], ['pre_incapacidad.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pre_incapacidad_id', 'validation_inconsistencia', ['pre_incapacidad_id'], unique=False)
    op.create_index('idx_incapacidad_id', 'validation_inconsistencia', ['incapacidad_id'], unique=False)
    op.create_index('idx_categoria', 'validation_inconsistencia', ['categoria'], unique=False)
    op.create_index('idx_severidad', 'validation_inconsistencia', ['severidad'], unique=False)
    op.create_index('ix_validation_inconsistencia_codigo', 'validation_inconsistencia', ['codigo'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('validation_inconsistencia')
    # ### end Alembic commands ###
