"""add_pre_incapacidad_pre_documento

Revision ID: 874da694b916
Revises: cf0a432a3aa8
Create Date: 2026-06-03 14:15:35.073075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '874da694b916'
down_revision: Union[str, None] = 'cf0a432a3aa8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Sequence para número de radicación secuencial (inicio: 202600001)
    op.execute("CREATE SEQUENCE IF NOT EXISTS pre_incapacidad_numero_seq START WITH 202600001 INCREMENT BY 1 NO CYCLE")
    op.create_table('pre_incapacidad',
    sa.Column('numero_radicacion', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False, comment='PENDIENTE | PROCESADA | RECHAZADA | ERROR'),
    sa.Column('solicitante_correo', sa.String(length=255), nullable=False),
    sa.Column('solicitante_nombres', sa.String(length=200), nullable=False),
    sa.Column('solicitante_apellidos', sa.String(length=200), nullable=True),
    sa.Column('solicitante_telefono', sa.String(length=20), nullable=True),
    sa.Column('empresa_nit', sa.String(length=20), nullable=True),
    sa.Column('empresa_nombre', sa.String(length=255), nullable=True),
    sa.Column('empleado_tipo_documento', sa.String(length=10), nullable=False),
    sa.Column('empleado_numero_documento', sa.String(length=20), nullable=False),
    sa.Column('empleado_nombres', sa.String(length=200), nullable=False),
    sa.Column('empleado_apellidos', sa.String(length=200), nullable=True),
    sa.Column('empleado_email', sa.String(length=255), nullable=True),
    sa.Column('empleado_telefono', sa.String(length=20), nullable=True),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('tipo_enfermedad', sa.String(length=50), nullable=False, comment='ACCIDENTE_TRABAJO | ENFERMEDAD_LABORAL | ACCIDENTE_TRAYECTO'),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('dias_totales', sa.Integer(), nullable=False),
    sa.Column('diagnostico_cie10', sa.String(length=10), nullable=False),
    sa.Column('descripcion_diagnostico', sa.Text(), nullable=True),
    sa.Column('nombre_medico', sa.String(length=200), nullable=False),
    sa.Column('registro_medico', sa.String(length=50), nullable=False),
    sa.Column('ips', sa.String(length=255), nullable=True),
    sa.Column('valor_dia', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('error_procesamiento', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pre_incapacidad_estado'), 'pre_incapacidad', ['estado'], unique=False)
    op.create_index(op.f('ix_pre_incapacidad_numero_radicacion'), 'pre_incapacidad', ['numero_radicacion'], unique=True)
    op.create_table('pre_documento',
    sa.Column('pre_incapacidad_id', sa.UUID(), nullable=False),
    sa.Column('tipo_documento', sa.String(length=50), nullable=False, comment='INCAPACIDAD_MEDICA | HISTORIA_CLINICA | SOPORTE_ADICIONAL'),
    sa.Column('nombre_original', sa.String(length=255), nullable=False),
    sa.Column('ruta_storage', sa.String(length=500), nullable=False),
    sa.Column('bucket', sa.String(length=100), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('tamanio_bytes', sa.BigInteger(), nullable=False),
    sa.Column('estado_subida', sa.String(length=10), nullable=False, comment='OK | ERROR'),
    sa.Column('error_subida', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['pre_incapacidad_id'], ['pre_incapacidad.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pre_documento_pre_incapacidad_id'), 'pre_documento', ['pre_incapacidad_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pre_documento_pre_incapacidad_id'), table_name='pre_documento')
    op.drop_table('pre_documento')
    op.drop_index(op.f('ix_pre_incapacidad_numero_radicacion'), table_name='pre_incapacidad')
    op.drop_index(op.f('ix_pre_incapacidad_estado'), table_name='pre_incapacidad')
    op.drop_table('pre_incapacidad')
    op.execute("DROP SEQUENCE IF EXISTS pre_incapacidad_numero_seq")
    # ### end Alembic commands ###
