"""add_smlmv_parametros_table

Revision ID: 87e66dac698e
Revises: dd865bb526a6
Create Date: 2026-07-29 19:29:42.124389

"""
import uuid
from datetime import date, datetime, timezone
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '87e66dac698e'
down_revision: Union[str, None] = 'dd865bb526a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


smlmv_parametros = sa.table(
    "smlmv_parametros",
    sa.column("id", sa.UUID()),
    sa.column("ano", sa.Integer()),
    sa.column("valor", sa.Numeric(precision=15, scale=2)),
    sa.column("vigente_desde", sa.Date()),
    sa.column("created_at", sa.DateTime(timezone=True)),
    sa.column("updated_at", sa.DateTime(timezone=True)),
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('smlmv_parametros',
    sa.Column('ano', sa.Integer(), nullable=False, comment='Año calendario al que aplica este SMLMV'),
    sa.Column('valor', sa.Numeric(precision=15, scale=2), nullable=False, comment='Valor del SMLMV en pesos colombianos, p.ej. 1750905.00'),
    sa.Column('vigente_desde', sa.Date(), nullable=False, comment='Fecha desde la cual es vigente este valor del SMLMV'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ano')
    )
    # ### end Alembic commands ###

    now = datetime.now(timezone.utc)
    op.bulk_insert(
        smlmv_parametros,
        [
            {
                "id": uuid.uuid4(),
                "ano": 2024,
                "valor": 1300000,
                "vigente_desde": date(2024, 1, 1),
                "created_at": now,
                "updated_at": now,
            },
            {
                "id": uuid.uuid4(),
                "ano": 2025,
                "valor": 1423500,
                "vigente_desde": date(2025, 1, 1),
                "created_at": now,
                "updated_at": now,
            },
            {
                "id": uuid.uuid4(),
                "ano": 2026,
                "valor": 1750905,
                "vigente_desde": date(2026, 1, 1),
                "created_at": now,
                "updated_at": now,
            },
        ],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('smlmv_parametros')
    # ### end Alembic commands ###
