"""agregar_solicitante_y_campos_medico

Revision ID: 541a0b02d056
Revises: d4d976c33c7f
Create Date: 2026-01-16 21:16:19.085194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '541a0b02d056'
down_revision: Union[str, None] = 'd4d976c33c7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Habilitar extensión pg_trgm para índices GIN de texto
    op.execute('CREATE EXTENSION IF NOT EXISTS pg_trgm;')
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalogo_cie10',
    sa.Column('codigo', sa.String(length=10), nullable=False, comment='Código CIE-10'),
    sa.Column('descripcion', sa.Text(), nullable=False, comment='Descripción del diagnóstico'),
    sa.PrimaryKeyConstraint('codigo')
    )
    op.create_index('idx_cie10_codigo_pattern', 'catalogo_cie10', ['codigo'], unique=False, postgresql_using='gin', postgresql_ops={'codigo': 'gin_trgm_ops'})
    op.create_index('idx_cie10_descripcion_fts', 'catalogo_cie10', ['descripcion'], unique=False, postgresql_using='gin', postgresql_ops={'descripcion': 'gin_trgm_ops'})
    op.create_table('solicitante',
    sa.Column('correo', sa.String(length=100), nullable=False, comment='Email del solicitante (único)'),
    sa.Column('nombres', sa.String(length=100), nullable=False, comment='Nombres del solicitante'),
    sa.Column('apellidos', sa.String(length=100), nullable=False, comment='Apellidos del solicitante'),
    sa.Column('telefono', sa.String(length=20), nullable=True, comment='Teléfono de contacto'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solicitante_correo'), 'solicitante', ['correo'], unique=True)
    op.add_column('incapacidad', sa.Column('solicitante_id', sa.UUID(), nullable=True, comment='Solicitante que radicó la incapacidad'))
    op.add_column('incapacidad', sa.Column('nombre_medico', sa.String(length=200), nullable=True, comment='Nombre completo del médico tratante'))
    op.add_column('incapacidad', sa.Column('registro_medico', sa.String(length=50), nullable=True, comment='Registro médico profesional'))
    op.create_index(op.f('ix_incapacidad_solicitante_id'), 'incapacidad', ['solicitante_id'], unique=False)
    op.create_foreign_key(None, 'incapacidad', 'solicitante', ['solicitante_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'incapacidad', type_='foreignkey')
    op.drop_index(op.f('ix_incapacidad_solicitante_id'), table_name='incapacidad')
    op.drop_column('incapacidad', 'registro_medico')
    op.drop_column('incapacidad', 'nombre_medico')
    op.drop_column('incapacidad', 'solicitante_id')
    op.drop_index(op.f('ix_solicitante_correo'), table_name='solicitante')
    op.drop_table('solicitante')
    op.drop_index('idx_cie10_descripcion_fts', table_name='catalogo_cie10', postgresql_using='gin', postgresql_ops={'descripcion': 'gin_trgm_ops'})
    op.drop_index('idx_cie10_codigo_pattern', table_name='catalogo_cie10', postgresql_using='gin', postgresql_ops={'codigo': 'gin_trgm_ops'})
    op.drop_table('catalogo_cie10')
    # ### end Alembic commands ###
    
    # Nota: No eliminamos la extensión pg_trgm en downgrade por seguridad
    # ya que podría estar siendo usada por otros índices
